language: node_js
node_js:
    - '12'
install:
    - yarn
script:
    - yarn format:check
    - yarn yarn audit
    - yarn test
    - yarn build
after_success:
    - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
