language: node_js
node_js:
    - '12'
script:
    - npm run format:check
    - npm audit
    - npm test
    - npm run build
after_success:
    - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
